version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
